name: CI 

on: [push]

jobs:
    
  hugo-server:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull origin master --recurse-submodules

      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker compose up -d
     
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Check running containers
        run: docker ps
